- id: bioRxiv:2025.06.09.658757
  type: paper
  description: Drug response prediction model
  image: 
  buttons:
    - type: source
      link: https://pmc.ncbi.nlm.nih.gov/articles/PMC12259075/figure/F1
  tags:
    - biology
    - big data
    - medicine
  repo: 

#Other
  - id: medRxiv:2025.06.10.25329327
  type: paper
  description: Sex-aware genetics.
  image: 
  buttons:
    - type: source
      link: https://www.medrxiv.org/content/medrxiv/early/2025/06/11/2025.06.10.25329327/F2.large.jpg
  tags:
    - biology
    - big data
    - medicine
  repo: 



