- id: bioRxiv:2025.06.09.658757
  type: paper
  description: Drug response prediction model
  image: 
  buttons:
    - type: source
      link: https://pmc.ncbi.nlm.nih.gov/articles/PMC12259075/figure/F1
  tags:
    - biology
    - big data
    - medicine
  repo: 



