- id: medRxiv 2025.06.10.25329327
  type: paper
  description: **Computational Tool**
  date: 2025-06-11
  image: 
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Repository
      link: https://github.com/boseb/GXwasR
    - type: source
      text: Tutorials
      link: https://github.com/boseb/GXwasR_Tutorials
  tags:
    - open science
    - collaboration

- id: doi:10.1101/2025.06.09.658757
  image: 


